name: Deploy to GitHub pages
on:
  push:
    # this is the branch where you develop your site
    # as discussed in the publishing sources section
    # this can change if you are using an user/organization repo
    branches:
        - main
        - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"

    - name: Run a multi-line script
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m sphinx doc_conf docs
        git config --global --add safe.directory /github/workspace/docs

    - name: Init new repo in dist folder and commit generated files
      run: |
        cd docs/
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./docs